# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1155, 460)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_segListLoad = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_segListLoad.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/import.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListLoad.setIcon(icon)
        self.pushButton_segListLoad.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListLoad.setObjectName("pushButton_segListLoad")
        self.horizontalLayout_3.addWidget(self.pushButton_segListLoad)
        self.pushButton_segListSave = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_segListSave.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListSave.setIcon(icon1)
        self.pushButton_segListSave.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListSave.setObjectName("pushButton_segListSave")
        self.horizontalLayout_3.addWidget(self.pushButton_segListSave)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_segListClear = QtWidgets.QPushButton(self.groupBox_8)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListClear.setIcon(icon2)
        self.pushButton_segListClear.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListClear.setObjectName("pushButton_segListClear")
        self.horizontalLayout_3.addWidget(self.pushButton_segListClear)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.table_segmentList = QtWidgets.QTableWidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_segmentList.sizePolicy().hasHeightForWidth())
        self.table_segmentList.setSizePolicy(sizePolicy)
        self.table_segmentList.setObjectName("table_segmentList")
        self.table_segmentList.setColumnCount(5)
        self.table_segmentList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.table_segmentList, 2, 1, 2, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_segListRowUp = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_segListRowUp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowUp.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowUp.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowUp.setIcon(icon3)
        self.pushButton_segListRowUp.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowUp.setObjectName("pushButton_segListRowUp")
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowUp)
        self.pushButton_segListRowDn = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_segListRowDn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDn.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowDn.setIcon(icon4)
        self.pushButton_segListRowDn.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowDn.setObjectName("pushButton_segListRowDn")
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowDn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_segListRowDel = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDel.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDel.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowDel.setIcon(icon5)
        self.pushButton_segListRowDel.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowDel.setObjectName("pushButton_segListRowDel")
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowDel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_objectDraw = QtWidgets.QPushButton(self.groupBox_8)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resources/draw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_objectDraw.setIcon(icon6)
        self.pushButton_objectDraw.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_objectDraw.setObjectName("pushButton_objectDraw")
        self.horizontalLayout_6.addWidget(self.pushButton_objectDraw)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 2, 1, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_angle = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_angle.sizePolicy().hasHeightForWidth())
        self.label_angle.setSizePolicy(sizePolicy)
        self.label_angle.setObjectName("label_angle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_angle)
        self.lineEdit_nextAzimuth = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextAzimuth.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextAzimuth.setSizePolicy(sizePolicy)
        self.lineEdit_nextAzimuth.setToolTip("")
        self.lineEdit_nextAzimuth.setObjectName("lineEdit_nextAzimuth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nextAzimuth)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_nextVertical = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_nextVertical.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextVertical.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextVertical.setSizePolicy(sizePolicy)
        self.lineEdit_nextVertical.setObjectName("lineEdit_nextVertical")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nextVertical)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_nextDistance = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextDistance.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextDistance.setSizePolicy(sizePolicy)
        self.lineEdit_nextDistance.setDecimals(3)
        self.lineEdit_nextDistance.setMaximum(999999999.0)
        self.lineEdit_nextDistance.setObjectName("lineEdit_nextDistance")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nextDistance)
        self.radiusLabel = QtWidgets.QLabel(self.groupBox_2)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        self.spin_radius = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_radius.sizePolicy().hasHeightForWidth())
        self.spin_radius.setSizePolicy(sizePolicy)
        self.spin_radius.setDecimals(3)
        self.spin_radius.setMaximum(999999999.0)
        self.spin_radius.setObjectName("spin_radius")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_radius)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_clockwise = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_clockwise.sizePolicy().hasHeightForWidth())
        self.radio_clockwise.setSizePolicy(sizePolicy)
        self.radio_clockwise.setObjectName("radio_clockwise")
        self.verticalLayout_4.addWidget(self.radio_clockwise)
        self.radio_anticlockwise = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_anticlockwise.sizePolicy().hasHeightForWidth())
        self.radio_anticlockwise.setSizePolicy(sizePolicy)
        self.radio_anticlockwise.setObjectName("radio_anticlockwise")
        self.verticalLayout_4.addWidget(self.radio_anticlockwise)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.pushButton_vertexInsert = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vertexInsert.sizePolicy().hasHeightForWidth())
        self.pushButton_vertexInsert.setSizePolicy(sizePolicy)
        self.pushButton_vertexInsert.setObjectName("pushButton_vertexInsert")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_vertexInsert)
        self.pushButton_vertexAdd = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vertexAdd.sizePolicy().hasHeightForWidth())
        self.pushButton_vertexAdd.setSizePolicy(sizePolicy)
        self.pushButton_vertexAdd.setObjectName("pushButton_vertexAdd")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_vertexAdd)
        self.offsetLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.offsetLabel.setFont(font)
        self.offsetLabel.setText("")
        self.offsetLabel.setObjectName("offsetLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.offsetLabel)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_vertexX0 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexX0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexX0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexX0.setObjectName("lineEdit_vertexX0")
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexX0)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_vertexY0 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexY0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexY0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexY0.setObjectName("lineEdit_vertexY0")
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexY0)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_vertexZ0 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_vertexZ0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexZ0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexZ0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexZ0.setObjectName("lineEdit_vertexZ0")
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexZ0)
        self.pushButton_startCapture = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_startCapture.sizePolicy().hasHeightForWidth())
        self.pushButton_startCapture.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/capture.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_startCapture.setIcon(icon7)
        self.pushButton_startCapture.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_startCapture.setObjectName("pushButton_startCapture")
        self.horizontalLayout_2.addWidget(self.pushButton_startCapture)
        self.pushButton_useLast = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_useLast.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useLast.sizePolicy().hasHeightForWidth())
        self.pushButton_useLast.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/resources/lastpoint.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_useLast.setIcon(icon8)
        self.pushButton_useLast.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_useLast.setObjectName("pushButton_useLast")
        self.horizontalLayout_2.addWidget(self.pushButton_useLast)
        self.pushButton_startCapture.raise_()
        self.lineEdit_vertexX0.raise_()
        self.label_2.raise_()
        self.lineEdit_vertexY0.raise_()
        self.label_3.raise_()
        self.lineEdit_vertexZ0.raise_()
        self.label_4.raise_()
        self.pushButton_useLast.raise_()
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_useMemoryLayer = QtWidgets.QRadioButton(self.tab)
        self.radioButton_useMemoryLayer.setObjectName("radioButton_useMemoryLayer")
        self.horizontalLayout_4.addWidget(self.radioButton_useMemoryLayer)
        self.radioButton_useActiveLayer = QtWidgets.QRadioButton(self.tab)
        self.radioButton_useActiveLayer.setObjectName("radioButton_useActiveLayer")
        self.horizontalLayout_4.addWidget(self.radioButton_useActiveLayer)
        self.label_5 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_crs = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_crs.setEnabled(False)
        self.lineEdit_crs.setObjectName("lineEdit_crs")
        self.horizontalLayout_4.addWidget(self.lineEdit_crs)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox1 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.arcNodesLabel = QtWidgets.QLabel(self.groupBox1)
        self.arcNodesLabel.setObjectName("arcNodesLabel")
        self.horizontalLayout.addWidget(self.arcNodesLabel)
        self.spin_arclines = QtWidgets.QSpinBox(self.groupBox1)
        self.spin_arclines.setMinimum(6)
        self.spin_arclines.setObjectName("spin_arclines")
        self.horizontalLayout.addWidget(self.spin_arclines)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBox_asSegments = QtWidgets.QCheckBox(self.groupBox1)
        self.checkBox_asSegments.setObjectName("checkBox_asSegments")
        self.verticalLayout_2.addWidget(self.checkBox_asSegments)
        self.checkBox_openForm = QtWidgets.QCheckBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_openForm.sizePolicy().hasHeightForWidth())
        self.checkBox_openForm.setSizePolicy(sizePolicy)
        self.checkBox_openForm.setChecked(True)
        self.checkBox_openForm.setObjectName("checkBox_openForm")
        self.verticalLayout_2.addWidget(self.checkBox_openForm)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_6.addWidget(self.groupBox1, 0, 6, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_defaultNorth = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_defaultNorth.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultNorth.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultNorth.setSizePolicy(sizePolicy)
        self.radioButton_defaultNorth.setCheckable(True)
        self.radioButton_defaultNorth.setChecked(True)
        self.radioButton_defaultNorth.setObjectName("radioButton_defaultNorth")
        self.verticalLayout_12.addWidget(self.radioButton_defaultNorth)
        self.radioButton_magNorth = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_magNorth.setEnabled(True)
        self.radioButton_magNorth.setChecked(False)
        self.radioButton_magNorth.setObjectName("radioButton_magNorth")
        self.verticalLayout_12.addWidget(self.radioButton_magNorth)
        self.lineEdit_magNorth = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_magNorth.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_magNorth.sizePolicy().hasHeightForWidth())
        self.lineEdit_magNorth.setSizePolicy(sizePolicy)
        self.lineEdit_magNorth.setText("")
        self.lineEdit_magNorth.setFrame(True)
        self.lineEdit_magNorth.setObjectName("lineEdit_magNorth")
        self.verticalLayout_12.addWidget(self.lineEdit_magNorth)
        self.formFrame = QtWidgets.QFrame(self.groupBox_3)
        self.formFrame.setEnabled(False)
        self.formFrame.setObjectName("formFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.azimuth1_edit = QtWidgets.QLineEdit(self.formFrame)
        self.azimuth1_edit.setObjectName("azimuth1_edit")
        self.horizontalLayout_11.addWidget(self.azimuth1_edit)
        self.pickAngle1_button = QtWidgets.QToolButton(self.formFrame)
        self.pickAngle1_button.setIcon(icon7)
        self.pickAngle1_button.setIconSize(QtCore.QSize(18, 18))
        self.pickAngle1_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pickAngle1_button.setObjectName("pickAngle1_button")
        self.horizontalLayout_11.addWidget(self.pickAngle1_button)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.azimuth2_edit = QtWidgets.QLineEdit(self.formFrame)
        self.azimuth2_edit.setObjectName("azimuth2_edit")
        self.horizontalLayout_10.addWidget(self.azimuth2_edit)
        self.pickAngle2_button = QtWidgets.QToolButton(self.formFrame)
        self.pickAngle2_button.setIcon(icon7)
        self.pickAngle2_button.setIconSize(QtCore.QSize(18, 18))
        self.pickAngle2_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pickAngle2_button.setObjectName("pickAngle2_button")
        self.horizontalLayout_10.addWidget(self.pickAngle2_button)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label = QtWidgets.QLabel(self.formFrame)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.azimuthDiff_edit = QtWidgets.QLineEdit(self.formFrame)
        self.azimuthDiff_edit.setObjectName("azimuthDiff_edit")
        self.horizontalLayout_5.addWidget(self.azimuthDiff_edit)
        self.copyDiff_button = QtWidgets.QToolButton(self.formFrame)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/resources/tick.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyDiff_button.setIcon(icon9)
        self.copyDiff_button.setIconSize(QtCore.QSize(18, 18))
        self.copyDiff_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.copyDiff_button.setObjectName("copyDiff_button")
        self.horizontalLayout_5.addWidget(self.copyDiff_button)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.clearMarkers_button = QtWidgets.QPushButton(self.formFrame)
        self.clearMarkers_button.setObjectName("clearMarkers_button")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.clearMarkers_button)
        self.verticalLayout_12.addWidget(self.formFrame)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 7, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.surveyGrpBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surveyGrpBox.sizePolicy().hasHeightForWidth())
        self.surveyGrpBox.setSizePolicy(sizePolicy)
        self.surveyGrpBox.setFlat(True)
        self.surveyGrpBox.setObjectName("surveyGrpBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.surveyGrpBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_radialSurvey = QtWidgets.QRadioButton(self.surveyGrpBox)
        self.radioButton_radialSurvey.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_radialSurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_radialSurvey.setSizePolicy(sizePolicy)
        self.radioButton_radialSurvey.setCheckable(True)
        self.radioButton_radialSurvey.setChecked(False)
        self.radioButton_radialSurvey.setObjectName("radioButton_radialSurvey")
        self.verticalLayout_10.addWidget(self.radioButton_radialSurvey)
        self.radioButton_boundarySurvey = QtWidgets.QRadioButton(self.surveyGrpBox)
        self.radioButton_boundarySurvey.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_boundarySurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_boundarySurvey.setSizePolicy(sizePolicy)
        self.radioButton_boundarySurvey.setChecked(True)
        self.radioButton_boundarySurvey.setObjectName("radioButton_boundarySurvey")
        self.verticalLayout_10.addWidget(self.radioButton_boundarySurvey)
        self.verticalLayout_6.addWidget(self.surveyGrpBox)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_azimuthAngle = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_azimuthAngle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_azimuthAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_azimuthAngle.setSizePolicy(sizePolicy)
        self.radioButton_azimuthAngle.setCheckable(True)
        self.radioButton_azimuthAngle.setChecked(True)
        self.radioButton_azimuthAngle.setObjectName("radioButton_azimuthAngle")
        self.verticalLayout_5.addWidget(self.radioButton_azimuthAngle)
        self.radioButton_bearingAngle = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_bearingAngle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_bearingAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_bearingAngle.setSizePolicy(sizePolicy)
        self.radioButton_bearingAngle.setChecked(False)
        self.radioButton_bearingAngle.setObjectName("radioButton_bearingAngle")
        self.verticalLayout_5.addWidget(self.radioButton_bearingAngle)
        self.radioButton_polarCoordAngle = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_polarCoordAngle.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_polarCoordAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_polarCoordAngle.setSizePolicy(sizePolicy)
        self.radioButton_polarCoordAngle.setChecked(False)
        self.radioButton_polarCoordAngle.setObjectName("radioButton_polarCoordAngle")
        self.verticalLayout_5.addWidget(self.radioButton_polarCoordAngle)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_distanceUnits = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_distanceUnits.setObjectName("comboBox_distanceUnits")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.comboBox_distanceUnits.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_distanceUnits)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.radioButton_degreeUnit = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_degreeUnit.sizePolicy().hasHeightForWidth())
        self.radioButton_degreeUnit.setSizePolicy(sizePolicy)
        self.radioButton_degreeUnit.setChecked(True)
        self.radioButton_degreeUnit.setObjectName("radioButton_degreeUnit")
        self.verticalLayout_31.addWidget(self.radioButton_degreeUnit)
        self.radioButton_gradianUnit = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_gradianUnit.sizePolicy().hasHeightForWidth())
        self.radioButton_gradianUnit.setSizePolicy(sizePolicy)
        self.radioButton_gradianUnit.setObjectName("radioButton_gradianUnit")
        self.verticalLayout_31.addWidget(self.radioButton_gradianUnit)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plainTextEdit_note = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_note.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_note.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_note.setSizePolicy(sizePolicy)
        self.plainTextEdit_note.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_note.setMaximumSize(QtCore.QSize(16777215, 100))
        self.plainTextEdit_note.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setReadOnly(True)
        self.plainTextEdit_note.setObjectName("plainTextEdit_note")
        self.gridLayout_5.addWidget(self.plainTextEdit_note, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_angle.setBuddy(self.lineEdit_nextAzimuth)
        self.label_12.setBuddy(self.lineEdit_nextVertical)
        self.label_13.setBuddy(self.lineEdit_nextDistance)
        self.label_2.setBuddy(self.lineEdit_vertexX0)
        self.label_3.setBuddy(self.lineEdit_vertexY0)
        self.label_4.setBuddy(self.lineEdit_vertexZ0)
        self.label_5.setBuddy(self.lineEdit_crs)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.radioButton_magNorth.toggled['bool'].connect(self.lineEdit_magNorth.setEnabled)
        self.radioButton_magNorth.toggled['bool'].connect(self.formFrame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_nextAzimuth, self.lineEdit_nextDistance)
        Form.setTabOrder(self.lineEdit_nextDistance, self.spin_radius)
        Form.setTabOrder(self.spin_radius, self.radio_clockwise)
        Form.setTabOrder(self.radio_clockwise, self.radio_anticlockwise)
        Form.setTabOrder(self.radio_anticlockwise, self.pushButton_vertexAdd)
        Form.setTabOrder(self.pushButton_vertexAdd, self.table_segmentList)
        Form.setTabOrder(self.table_segmentList, self.pushButton_segListLoad)
        Form.setTabOrder(self.pushButton_segListLoad, self.pushButton_segListSave)
        Form.setTabOrder(self.pushButton_segListSave, self.pushButton_segListClear)
        Form.setTabOrder(self.pushButton_segListClear, self.lineEdit_crs)
        Form.setTabOrder(self.lineEdit_crs, self.radioButton_useMemoryLayer)
        Form.setTabOrder(self.radioButton_useMemoryLayer, self.radioButton_useActiveLayer)
        Form.setTabOrder(self.radioButton_useActiveLayer, self.radioButton_radialSurvey)
        Form.setTabOrder(self.radioButton_radialSurvey, self.radioButton_boundarySurvey)
        Form.setTabOrder(self.radioButton_boundarySurvey, self.radioButton_defaultNorth)
        Form.setTabOrder(self.radioButton_defaultNorth, self.radioButton_magNorth)
        Form.setTabOrder(self.radioButton_magNorth, self.lineEdit_magNorth)
        Form.setTabOrder(self.lineEdit_magNorth, self.radioButton_azimuthAngle)
        Form.setTabOrder(self.radioButton_azimuthAngle, self.radioButton_bearingAngle)
        Form.setTabOrder(self.radioButton_bearingAngle, self.radioButton_polarCoordAngle)
        Form.setTabOrder(self.radioButton_polarCoordAngle, self.spin_arclines)
        Form.setTabOrder(self.spin_arclines, self.plainTextEdit_note)
        Form.setTabOrder(self.plainTextEdit_note, self.checkBox_asSegments)
        Form.setTabOrder(self.checkBox_asSegments, self.checkBox_openForm)
        Form.setTabOrder(self.checkBox_openForm, self.lineEdit_nextVertical)
        Form.setTabOrder(self.lineEdit_nextVertical, self.lineEdit_vertexX0)
        Form.setTabOrder(self.lineEdit_vertexX0, self.lineEdit_vertexY0)
        Form.setTabOrder(self.lineEdit_vertexY0, self.lineEdit_vertexZ0)
        Form.setTabOrder(self.lineEdit_vertexZ0, self.pushButton_startCapture)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_8.setTitle(_translate("Form", "Segment List"))
        self.pushButton_segListLoad.setToolTip(_translate("Form", "Import Segment List"))
        self.pushButton_segListLoad.setText(_translate("Form", "Import"))
        self.pushButton_segListSave.setToolTip(_translate("Form", "Export Segment List"))
        self.pushButton_segListSave.setText(_translate("Form", "Export"))
        self.pushButton_segListClear.setToolTip(_translate("Form", "Clear Segment List"))
        self.pushButton_segListClear.setText(_translate("Form", "Clear List"))
        item = self.table_segmentList.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Azimuth"))
        item = self.table_segmentList.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Distance"))
        item = self.table_segmentList.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Zenith Angle"))
        item = self.table_segmentList.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Radius"))
        item = self.table_segmentList.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Direction"))
        item.setToolTip(_translate("Form", "Supported values are \'anticlockwise\', \'a\', \'c\', \'clockwise\'"))
        self.pushButton_segListRowUp.setToolTip(_translate("Form", "Move Selected Segment Up"))
        self.pushButton_segListRowUp.setText(_translate("Form", "Move Up"))
        self.pushButton_segListRowDn.setToolTip(_translate("Form", "Move Selected Segment Down"))
        self.pushButton_segListRowDn.setText(_translate("Form", "Move Down"))
        self.pushButton_segListRowDel.setToolTip(_translate("Form", "Remove Selected Segment"))
        self.pushButton_segListRowDel.setText(_translate("Form", "Remove"))
        self.pushButton_objectDraw.setToolTip(_translate("Form", "Draw Segment List"))
        self.pushButton_objectDraw.setText(_translate("Form", "Draw"))
        self.groupBox_2.setTitle(_translate("Form", "Next vertex"))
        self.label_angle.setText(_translate("Form", "Azimuth:"))
        self.lineEdit_nextAzimuth.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "Zenith:"))
        self.lineEdit_nextVertical.setText(_translate("Form", "90"))
        self.label_13.setText(_translate("Form", "Distance:"))
        self.radiusLabel.setText(_translate("Form", "Arc Radius"))
        self.label_6.setText(_translate("Form", "Arc Direction"))
        self.radio_clockwise.setText(_translate("Form", "Clockwise"))
        self.radio_anticlockwise.setText(_translate("Form", "Anti-clockwise"))
        self.pushButton_vertexInsert.setToolTip(_translate("Form", "Insert New Segment Above Currently Selected Segment"))
        self.pushButton_vertexInsert.setText(_translate("Form", "Insert Above"))
        self.pushButton_vertexAdd.setToolTip(_translate("Form", "Add New Segment to Bottom of List"))
        self.pushButton_vertexAdd.setText(_translate("Form", "Add to Bottom"))
        self.label_9.setText(_translate("Form", "Offset"))
        self.groupBox.setTitle(_translate("Form", "Starting point"))
        self.label_2.setText(_translate("Form", "X"))
        self.lineEdit_vertexX0.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "Y"))
        self.lineEdit_vertexY0.setText(_translate("Form", "0"))
        self.label_4.setText(_translate("Form", "Z"))
        self.lineEdit_vertexZ0.setText(_translate("Form", "0"))
        self.pushButton_startCapture.setToolTip(_translate("Form", "Select Starting Point from Map"))
        self.pushButton_startCapture.setText(_translate("Form", "From Map"))
        self.pushButton_useLast.setToolTip(_translate("Form", "Use Last Vertex as Starting Point"))
        self.pushButton_useLast.setText(_translate("Form", "Use Last Vertex"))
        self.radioButton_useMemoryLayer.setText(_translate("Form", "Memory Layer"))
        self.radioButton_useActiveLayer.setText(_translate("Form", "Active Layer"))
        self.label_5.setText(_translate("Form", "Coordinate System:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Drawing"))
        self.groupBox1.setTitle(_translate("Form", "Drawing"))
        self.arcNodesLabel.setToolTip(_translate("Form", "The more lines the smoother the arc will be"))
        self.arcNodesLabel.setText(_translate("Form", "Arc lines"))
        self.spin_arclines.setToolTip(_translate("Form", "The more lines the smoother the arc will be"))
        self.checkBox_asSegments.setText(_translate("Form", "As Segments"))
        self.checkBox_openForm.setText(_translate("Form", "Open attribute form"))
        self.groupBox_3.setTitle(_translate("Form", "North type"))
        self.radioButton_defaultNorth.setText(_translate("Form", "Default"))
        self.radioButton_magNorth.setText(_translate("Form", "Magnetic"))
        self.lineEdit_magNorth.setPlaceholderText(_translate("Form", "Magnetic offset"))
        self.azimuth1_edit.setText(_translate("Form", "0"))
        self.pickAngle1_button.setText(_translate("Form", "Pick Points"))
        self.label_7.setText(_translate("Form", "Azimuth 2"))
        self.azimuth2_edit.setText(_translate("Form", "0"))
        self.pickAngle2_button.setText(_translate("Form", "Pick Points"))
        self.label.setText(_translate("Form", "Azimuth Diff"))
        self.copyDiff_button.setText(_translate("Form", "Use Value"))
        self.label_8.setText(_translate("Form", "Azimuth 1"))
        self.clearMarkers_button.setText(_translate("Form", "Clear angle markers"))
        self.surveyGrpBox.setTitle(_translate("Form", "Survey type"))
        self.radioButton_radialSurvey.setText(_translate("Form", "Polar / Radial"))
        self.radioButton_boundarySurvey.setText(_translate("Form", "Boundary"))
        self.groupBox_6.setTitle(_translate("Form", "Angle type"))
        self.radioButton_azimuthAngle.setText(_translate("Form", "Azimuth"))
        self.radioButton_bearingAngle.setText(_translate("Form", "Bearing"))
        self.radioButton_polarCoordAngle.setText(_translate("Form", "Polar coordinates"))
        self.groupBox_7.setTitle(_translate("Form", "Distance unit"))
        self.comboBox_distanceUnits.setItemText(0, _translate("Form", "Default"))
        self.comboBox_distanceUnits.setItemText(1, _translate("Form", "Centimeters"))
        self.comboBox_distanceUnits.setItemText(2, _translate("Form", "Feet"))
        self.comboBox_distanceUnits.setItemText(3, _translate("Form", "Kilometers"))
        self.comboBox_distanceUnits.setItemText(4, _translate("Form", "Meters"))
        self.comboBox_distanceUnits.setItemText(5, _translate("Form", "Miles"))
        self.comboBox_distanceUnits.setItemText(6, _translate("Form", "Millimeters"))
        self.comboBox_distanceUnits.setItemText(7, _translate("Form", "Nautical Miles"))
        self.comboBox_distanceUnits.setItemText(8, _translate("Form", "Yards"))
        self.groupBox_4.setTitle(_translate("Form", "Angle unit"))
        self.radioButton_degreeUnit.setText(_translate("Form", "Degree"))
        self.radioButton_gradianUnit.setText(_translate("Form", "Gradian"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Options"))
        self.plainTextEdit_note.setPlainText(_translate("Form", "Angles may be entered as degrees clockwise from North (nnn.nn or nnd nn\' nn.n\") or as an offset bearing plus or minus 90 deg. from  North or South (N xxd xx\' xx\" E)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Help"))

from . import resources_rc
