# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1155, 460)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_segListLoad = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_segListLoad.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/import.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListLoad.setIcon(icon)
        self.pushButton_segListLoad.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListLoad.setObjectName(_fromUtf8("pushButton_segListLoad"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListLoad)
        self.pushButton_segListSave = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_segListSave.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/export.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListSave.setIcon(icon1)
        self.pushButton_segListSave.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListSave.setObjectName(_fromUtf8("pushButton_segListSave"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListSave)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_segListClear = QtGui.QPushButton(self.groupBox_8)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/clear.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListClear.setIcon(icon2)
        self.pushButton_segListClear.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListClear.setObjectName(_fromUtf8("pushButton_segListClear"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListClear)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.table_segmentList = QtGui.QTableWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_segmentList.sizePolicy().hasHeightForWidth())
        self.table_segmentList.setSizePolicy(sizePolicy)
        self.table_segmentList.setObjectName(_fromUtf8("table_segmentList"))
        self.table_segmentList.setColumnCount(5)
        self.table_segmentList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.table_segmentList, 2, 1, 2, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_segListRowUp = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_segListRowUp.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowUp.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowUp.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowUp.setIcon(icon3)
        self.pushButton_segListRowUp.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowUp.setObjectName(_fromUtf8("pushButton_segListRowUp"))
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowUp)
        self.pushButton_segListRowDn = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_segListRowDn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDn.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/down.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowDn.setIcon(icon4)
        self.pushButton_segListRowDn.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowDn.setObjectName(_fromUtf8("pushButton_segListRowDn"))
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowDn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_segListRowDel = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDel.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDel.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/remove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_segListRowDel.setIcon(icon5)
        self.pushButton_segListRowDel.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_segListRowDel.setObjectName(_fromUtf8("pushButton_segListRowDel"))
        self.horizontalLayout_6.addWidget(self.pushButton_segListRowDel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_objectDraw = QtGui.QPushButton(self.groupBox_8)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/draw.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_objectDraw.setIcon(icon6)
        self.pushButton_objectDraw.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_objectDraw.setObjectName(_fromUtf8("pushButton_objectDraw"))
        self.horizontalLayout_6.addWidget(self.pushButton_objectDraw)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 2, 1, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_nextAzimuth = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextAzimuth.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextAzimuth.setSizePolicy(sizePolicy)
        self.lineEdit_nextAzimuth.setToolTip(_fromUtf8(""))
        self.lineEdit_nextAzimuth.setObjectName(_fromUtf8("lineEdit_nextAzimuth"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_nextAzimuth)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_nextVertical = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_nextVertical.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextVertical.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextVertical.setSizePolicy(sizePolicy)
        self.lineEdit_nextVertical.setObjectName(_fromUtf8("lineEdit_nextVertical"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_nextVertical)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_nextDistance = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextDistance.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextDistance.setSizePolicy(sizePolicy)
        self.lineEdit_nextDistance.setMaximum(999999999.0)
        self.lineEdit_nextDistance.setObjectName(_fromUtf8("lineEdit_nextDistance"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_nextDistance)
        self.radiusLabel = QtGui.QLabel(self.groupBox_2)
        self.radiusLabel.setObjectName(_fromUtf8("radiusLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.radiusLabel)
        self.spin_radius = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_radius.sizePolicy().hasHeightForWidth())
        self.spin_radius.setSizePolicy(sizePolicy)
        self.spin_radius.setMaximum(999999999.0)
        self.spin_radius.setObjectName(_fromUtf8("spin_radius"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spin_radius)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radio_clockwise = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_clockwise.sizePolicy().hasHeightForWidth())
        self.radio_clockwise.setSizePolicy(sizePolicy)
        self.radio_clockwise.setObjectName(_fromUtf8("radio_clockwise"))
        self.verticalLayout_4.addWidget(self.radio_clockwise)
        self.radio_anticlockwise = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_anticlockwise.sizePolicy().hasHeightForWidth())
        self.radio_anticlockwise.setSizePolicy(sizePolicy)
        self.radio_anticlockwise.setObjectName(_fromUtf8("radio_anticlockwise"))
        self.verticalLayout_4.addWidget(self.radio_anticlockwise)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.verticalLayout_4)
        self.pushButton_vertexInsert = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vertexInsert.sizePolicy().hasHeightForWidth())
        self.pushButton_vertexInsert.setSizePolicy(sizePolicy)
        self.pushButton_vertexInsert.setObjectName(_fromUtf8("pushButton_vertexInsert"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.pushButton_vertexInsert)
        self.pushButton_vertexAdd = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vertexAdd.sizePolicy().hasHeightForWidth())
        self.pushButton_vertexAdd.setSizePolicy(sizePolicy)
        self.pushButton_vertexAdd.setObjectName(_fromUtf8("pushButton_vertexAdd"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.pushButton_vertexAdd)
        self.offsetLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.offsetLabel.setFont(font)
        self.offsetLabel.setText(_fromUtf8(""))
        self.offsetLabel.setObjectName(_fromUtf8("offsetLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.offsetLabel)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setMargin(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_vertexX0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexX0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexX0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexX0.setObjectName(_fromUtf8("lineEdit_vertexX0"))
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexX0)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_vertexY0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexY0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexY0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexY0.setObjectName(_fromUtf8("lineEdit_vertexY0"))
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexY0)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_vertexZ0 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_vertexZ0.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexZ0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexZ0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexZ0.setObjectName(_fromUtf8("lineEdit_vertexZ0"))
        self.horizontalLayout_2.addWidget(self.lineEdit_vertexZ0)
        self.pushButton_startCapture = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_startCapture.sizePolicy().hasHeightForWidth())
        self.pushButton_startCapture.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/capture.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_startCapture.setIcon(icon7)
        self.pushButton_startCapture.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_startCapture.setObjectName(_fromUtf8("pushButton_startCapture"))
        self.horizontalLayout_2.addWidget(self.pushButton_startCapture)
        self.pushButton_useLast = QtGui.QPushButton(self.groupBox)
        self.pushButton_useLast.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useLast.sizePolicy().hasHeightForWidth())
        self.pushButton_useLast.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/lastpoint.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_useLast.setIcon(icon8)
        self.pushButton_useLast.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_useLast.setObjectName(_fromUtf8("pushButton_useLast"))
        self.horizontalLayout_2.addWidget(self.pushButton_useLast)
        self.pushButton_startCapture.raise_()
        self.lineEdit_vertexX0.raise_()
        self.label_2.raise_()
        self.lineEdit_vertexY0.raise_()
        self.label_3.raise_()
        self.lineEdit_vertexZ0.raise_()
        self.label_4.raise_()
        self.pushButton_useLast.raise_()
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_useMemoryLayer = QtGui.QRadioButton(self.tab)
        self.radioButton_useMemoryLayer.setObjectName(_fromUtf8("radioButton_useMemoryLayer"))
        self.horizontalLayout_4.addWidget(self.radioButton_useMemoryLayer)
        self.radioButton_useActiveLayer = QtGui.QRadioButton(self.tab)
        self.radioButton_useActiveLayer.setObjectName(_fromUtf8("radioButton_useActiveLayer"))
        self.horizontalLayout_4.addWidget(self.radioButton_useActiveLayer)
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_crs = QtGui.QLineEdit(self.tab)
        self.lineEdit_crs.setEnabled(False)
        self.lineEdit_crs.setObjectName(_fromUtf8("lineEdit_crs"))
        self.horizontalLayout_4.addWidget(self.lineEdit_crs)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox1 = QtGui.QGroupBox(self.tab_2)
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.arcNodesLabel = QtGui.QLabel(self.groupBox1)
        self.arcNodesLabel.setObjectName(_fromUtf8("arcNodesLabel"))
        self.horizontalLayout.addWidget(self.arcNodesLabel)
        self.spin_arclines = QtGui.QSpinBox(self.groupBox1)
        self.spin_arclines.setMinimum(6)
        self.spin_arclines.setObjectName(_fromUtf8("spin_arclines"))
        self.horizontalLayout.addWidget(self.spin_arclines)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBox_asSegments = QtGui.QCheckBox(self.groupBox1)
        self.checkBox_asSegments.setObjectName(_fromUtf8("checkBox_asSegments"))
        self.verticalLayout_2.addWidget(self.checkBox_asSegments)
        self.checkBox_openForm = QtGui.QCheckBox(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_openForm.sizePolicy().hasHeightForWidth())
        self.checkBox_openForm.setSizePolicy(sizePolicy)
        self.checkBox_openForm.setChecked(True)
        self.checkBox_openForm.setObjectName(_fromUtf8("checkBox_openForm"))
        self.verticalLayout_2.addWidget(self.checkBox_openForm)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_6.addWidget(self.groupBox1, 0, 6, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 1, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.radioButton_defaultNorth = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_defaultNorth.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultNorth.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultNorth.setSizePolicy(sizePolicy)
        self.radioButton_defaultNorth.setCheckable(True)
        self.radioButton_defaultNorth.setChecked(True)
        self.radioButton_defaultNorth.setObjectName(_fromUtf8("radioButton_defaultNorth"))
        self.verticalLayout_12.addWidget(self.radioButton_defaultNorth)
        self.radioButton_magNorth = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_magNorth.setEnabled(True)
        self.radioButton_magNorth.setChecked(False)
        self.radioButton_magNorth.setObjectName(_fromUtf8("radioButton_magNorth"))
        self.verticalLayout_12.addWidget(self.radioButton_magNorth)
        self.lineEdit_magNorth = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_magNorth.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_magNorth.sizePolicy().hasHeightForWidth())
        self.lineEdit_magNorth.setSizePolicy(sizePolicy)
        self.lineEdit_magNorth.setText(_fromUtf8(""))
        self.lineEdit_magNorth.setFrame(True)
        self.lineEdit_magNorth.setObjectName(_fromUtf8("lineEdit_magNorth"))
        self.verticalLayout_12.addWidget(self.lineEdit_magNorth)
        self.formFrame = QtGui.QFrame(self.groupBox_3)
        self.formFrame.setEnabled(False)
        self.formFrame.setObjectName(_fromUtf8("formFrame"))
        self.formLayout_2 = QtGui.QFormLayout(self.formFrame)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.azimuth1_edit = QtGui.QLineEdit(self.formFrame)
        self.azimuth1_edit.setObjectName(_fromUtf8("azimuth1_edit"))
        self.horizontalLayout_11.addWidget(self.azimuth1_edit)
        self.pickAngle1_button = QtGui.QToolButton(self.formFrame)
        self.pickAngle1_button.setIcon(icon7)
        self.pickAngle1_button.setIconSize(QtCore.QSize(18, 18))
        self.pickAngle1_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pickAngle1_button.setObjectName(_fromUtf8("pickAngle1_button"))
        self.horizontalLayout_11.addWidget(self.pickAngle1_button)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_7 = QtGui.QLabel(self.formFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.azimuth2_edit = QtGui.QLineEdit(self.formFrame)
        self.azimuth2_edit.setObjectName(_fromUtf8("azimuth2_edit"))
        self.horizontalLayout_10.addWidget(self.azimuth2_edit)
        self.pickAngle2_button = QtGui.QToolButton(self.formFrame)
        self.pickAngle2_button.setIcon(icon7)
        self.pickAngle2_button.setIconSize(QtCore.QSize(18, 18))
        self.pickAngle2_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pickAngle2_button.setObjectName(_fromUtf8("pickAngle2_button"))
        self.horizontalLayout_10.addWidget(self.pickAngle2_button)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label = QtGui.QLabel(self.formFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.azimuthDiff_edit = QtGui.QLineEdit(self.formFrame)
        self.azimuthDiff_edit.setObjectName(_fromUtf8("azimuthDiff_edit"))
        self.horizontalLayout_5.addWidget(self.azimuthDiff_edit)
        self.copyDiff_button = QtGui.QToolButton(self.formFrame)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/resources/tick.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyDiff_button.setIcon(icon9)
        self.copyDiff_button.setIconSize(QtCore.QSize(18, 18))
        self.copyDiff_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.copyDiff_button.setObjectName(_fromUtf8("copyDiff_button"))
        self.horizontalLayout_5.addWidget(self.copyDiff_button)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_8 = QtGui.QLabel(self.formFrame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.clearMarkers_button = QtGui.QPushButton(self.formFrame)
        self.clearMarkers_button.setObjectName(_fromUtf8("clearMarkers_button"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.clearMarkers_button)
        self.verticalLayout_12.addWidget(self.formFrame)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 7, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.surveyGrpBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surveyGrpBox.sizePolicy().hasHeightForWidth())
        self.surveyGrpBox.setSizePolicy(sizePolicy)
        self.surveyGrpBox.setFlat(True)
        self.surveyGrpBox.setObjectName(_fromUtf8("surveyGrpBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.surveyGrpBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.radioButton_radialSurvey = QtGui.QRadioButton(self.surveyGrpBox)
        self.radioButton_radialSurvey.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_radialSurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_radialSurvey.setSizePolicy(sizePolicy)
        self.radioButton_radialSurvey.setCheckable(True)
        self.radioButton_radialSurvey.setChecked(False)
        self.radioButton_radialSurvey.setObjectName(_fromUtf8("radioButton_radialSurvey"))
        self.verticalLayout_10.addWidget(self.radioButton_radialSurvey)
        self.radioButton_boundarySurvey = QtGui.QRadioButton(self.surveyGrpBox)
        self.radioButton_boundarySurvey.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_boundarySurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_boundarySurvey.setSizePolicy(sizePolicy)
        self.radioButton_boundarySurvey.setChecked(True)
        self.radioButton_boundarySurvey.setObjectName(_fromUtf8("radioButton_boundarySurvey"))
        self.verticalLayout_10.addWidget(self.radioButton_boundarySurvey)
        self.verticalLayout_6.addWidget(self.surveyGrpBox)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_azimuthAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_azimuthAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_azimuthAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_azimuthAngle.setSizePolicy(sizePolicy)
        self.radioButton_azimuthAngle.setCheckable(True)
        self.radioButton_azimuthAngle.setChecked(True)
        self.radioButton_azimuthAngle.setObjectName(_fromUtf8("radioButton_azimuthAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_azimuthAngle)
        self.radioButton_bearingAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_bearingAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_bearingAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_bearingAngle.setSizePolicy(sizePolicy)
        self.radioButton_bearingAngle.setChecked(False)
        self.radioButton_bearingAngle.setObjectName(_fromUtf8("radioButton_bearingAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_bearingAngle)
        self.radioButton_polarCoordAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_polarCoordAngle.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_polarCoordAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_polarCoordAngle.setSizePolicy(sizePolicy)
        self.radioButton_polarCoordAngle.setChecked(False)
        self.radioButton_polarCoordAngle.setObjectName(_fromUtf8("radioButton_polarCoordAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_polarCoordAngle)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_defaultUnits = QtGui.QRadioButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultUnits.setSizePolicy(sizePolicy)
        self.radioButton_defaultUnits.setChecked(True)
        self.radioButton_defaultUnits.setObjectName(_fromUtf8("radioButton_defaultUnits"))
        self.verticalLayout_3.addWidget(self.radioButton_defaultUnits)
        self.radioButton_englishUnits = QtGui.QRadioButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_englishUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_englishUnits.setSizePolicy(sizePolicy)
        self.radioButton_englishUnits.setObjectName(_fromUtf8("radioButton_englishUnits"))
        self.verticalLayout_3.addWidget(self.radioButton_englishUnits)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.radioButton_degreeUnit = QtGui.QRadioButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_degreeUnit.sizePolicy().hasHeightForWidth())
        self.radioButton_degreeUnit.setSizePolicy(sizePolicy)
        self.radioButton_degreeUnit.setChecked(True)
        self.radioButton_degreeUnit.setObjectName(_fromUtf8("radioButton_degreeUnit"))
        self.verticalLayout_31.addWidget(self.radioButton_degreeUnit)
        self.radioButton_gradianUnit = QtGui.QRadioButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_gradianUnit.sizePolicy().hasHeightForWidth())
        self.radioButton_gradianUnit.setSizePolicy(sizePolicy)
        self.radioButton_gradianUnit.setObjectName(_fromUtf8("radioButton_gradianUnit"))
        self.verticalLayout_31.addWidget(self.radioButton_gradianUnit)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plainTextEdit_note = QtGui.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_note.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_note.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_note.setSizePolicy(sizePolicy)
        self.plainTextEdit_note.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit_note.setMaximumSize(QtCore.QSize(16777215, 100))
        self.plainTextEdit_note.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setReadOnly(True)
        self.plainTextEdit_note.setObjectName(_fromUtf8("plainTextEdit_note"))
        self.gridLayout_5.addWidget(self.plainTextEdit_note, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_11.setBuddy(self.lineEdit_nextAzimuth)
        self.label_12.setBuddy(self.lineEdit_nextVertical)
        self.label_13.setBuddy(self.lineEdit_nextDistance)
        self.label_2.setBuddy(self.lineEdit_vertexX0)
        self.label_3.setBuddy(self.lineEdit_vertexY0)
        self.label_4.setBuddy(self.lineEdit_vertexZ0)
        self.label_5.setBuddy(self.lineEdit_crs)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.radioButton_magNorth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_magNorth.setEnabled)
        QtCore.QObject.connect(self.radioButton_magNorth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.formFrame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_nextAzimuth, self.lineEdit_nextDistance)
        Form.setTabOrder(self.lineEdit_nextDistance, self.spin_radius)
        Form.setTabOrder(self.spin_radius, self.radio_clockwise)
        Form.setTabOrder(self.radio_clockwise, self.radio_anticlockwise)
        Form.setTabOrder(self.radio_anticlockwise, self.pushButton_vertexAdd)
        Form.setTabOrder(self.pushButton_vertexAdd, self.table_segmentList)
        Form.setTabOrder(self.table_segmentList, self.pushButton_segListLoad)
        Form.setTabOrder(self.pushButton_segListLoad, self.pushButton_segListSave)
        Form.setTabOrder(self.pushButton_segListSave, self.pushButton_segListClear)
        Form.setTabOrder(self.pushButton_segListClear, self.lineEdit_crs)
        Form.setTabOrder(self.lineEdit_crs, self.radioButton_useMemoryLayer)
        Form.setTabOrder(self.radioButton_useMemoryLayer, self.radioButton_useActiveLayer)
        Form.setTabOrder(self.radioButton_useActiveLayer, self.radioButton_radialSurvey)
        Form.setTabOrder(self.radioButton_radialSurvey, self.radioButton_boundarySurvey)
        Form.setTabOrder(self.radioButton_boundarySurvey, self.radioButton_defaultNorth)
        Form.setTabOrder(self.radioButton_defaultNorth, self.radioButton_magNorth)
        Form.setTabOrder(self.radioButton_magNorth, self.lineEdit_magNorth)
        Form.setTabOrder(self.lineEdit_magNorth, self.radioButton_englishUnits)
        Form.setTabOrder(self.radioButton_englishUnits, self.radioButton_azimuthAngle)
        Form.setTabOrder(self.radioButton_azimuthAngle, self.radioButton_bearingAngle)
        Form.setTabOrder(self.radioButton_bearingAngle, self.radioButton_polarCoordAngle)
        Form.setTabOrder(self.radioButton_polarCoordAngle, self.spin_arclines)
        Form.setTabOrder(self.spin_arclines, self.plainTextEdit_note)
        Form.setTabOrder(self.plainTextEdit_note, self.checkBox_asSegments)
        Form.setTabOrder(self.checkBox_asSegments, self.checkBox_openForm)
        Form.setTabOrder(self.checkBox_openForm, self.lineEdit_nextVertical)
        Form.setTabOrder(self.lineEdit_nextVertical, self.lineEdit_vertexX0)
        Form.setTabOrder(self.lineEdit_vertexX0, self.lineEdit_vertexY0)
        Form.setTabOrder(self.lineEdit_vertexY0, self.lineEdit_vertexZ0)
        Form.setTabOrder(self.lineEdit_vertexZ0, self.pushButton_startCapture)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_8.setTitle(_translate("Form", "Segment List", None))
        self.pushButton_segListLoad.setToolTip(_translate("Form", "Import Segment List", None))
        self.pushButton_segListLoad.setText(_translate("Form", "Import", None))
        self.pushButton_segListSave.setToolTip(_translate("Form", "Export Segment List", None))
        self.pushButton_segListSave.setText(_translate("Form", "Export", None))
        self.pushButton_segListClear.setToolTip(_translate("Form", "Clear Segment List", None))
        self.pushButton_segListClear.setText(_translate("Form", "Clear List", None))
        item = self.table_segmentList.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Azimuth", None))
        item = self.table_segmentList.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Distance", None))
        item = self.table_segmentList.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Vertical Angle", None))
        item = self.table_segmentList.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Radius", None))
        item = self.table_segmentList.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Direction", None))
        item.setToolTip(_translate("Form", "Supported values are \'anticlockwise\', \'a\', \'c\', \'clockwise\'", None))
        self.pushButton_segListRowUp.setToolTip(_translate("Form", "Move Selected Segment Up", None))
        self.pushButton_segListRowUp.setText(_translate("Form", "Move Up", None))
        self.pushButton_segListRowDn.setToolTip(_translate("Form", "Move Selected Segment Down", None))
        self.pushButton_segListRowDn.setText(_translate("Form", "Move Down", None))
        self.pushButton_segListRowDel.setToolTip(_translate("Form", "Remove Selected Segment", None))
        self.pushButton_segListRowDel.setText(_translate("Form", "Remove", None))
        self.pushButton_objectDraw.setToolTip(_translate("Form", "Draw Segment List", None))
        self.pushButton_objectDraw.setText(_translate("Form", "Draw", None))
        self.groupBox_2.setTitle(_translate("Form", "Next vertex", None))
        self.label_11.setText(_translate("Form", "Azimuth:", None))
        self.lineEdit_nextAzimuth.setText(_translate("Form", "0", None))
        self.label_12.setText(_translate("Form", "Vertical:", None))
        self.lineEdit_nextVertical.setText(_translate("Form", "90", None))
        self.label_13.setText(_translate("Form", "Distance:", None))
        self.radiusLabel.setText(_translate("Form", "Arc Radius", None))
        self.label_6.setText(_translate("Form", "Arc Direction", None))
        self.radio_clockwise.setText(_translate("Form", "Clockwise", None))
        self.radio_anticlockwise.setText(_translate("Form", "Anti-clockwise", None))
        self.pushButton_vertexInsert.setToolTip(_translate("Form", "Insert New Segment Above Currently Selected Segment", None))
        self.pushButton_vertexInsert.setText(_translate("Form", "Insert Above", None))
        self.pushButton_vertexAdd.setToolTip(_translate("Form", "Add New Segment to Bottom of List", None))
        self.pushButton_vertexAdd.setText(_translate("Form", "Add to Bottom", None))
        self.label_9.setText(_translate("Form", "Offset", None))
        self.groupBox.setTitle(_translate("Form", "Starting point", None))
        self.label_2.setText(_translate("Form", "X", None))
        self.lineEdit_vertexX0.setText(_translate("Form", "0", None))
        self.label_3.setText(_translate("Form", "Y", None))
        self.lineEdit_vertexY0.setText(_translate("Form", "0", None))
        self.label_4.setText(_translate("Form", "Z", None))
        self.lineEdit_vertexZ0.setText(_translate("Form", "0", None))
        self.pushButton_startCapture.setToolTip(_translate("Form", "Select Starting Point from Map", None))
        self.pushButton_startCapture.setText(_translate("Form", "From Map", None))
        self.pushButton_useLast.setToolTip(_translate("Form", "Use Last Vertex as Starting Point", None))
        self.pushButton_useLast.setText(_translate("Form", "Use Last Vertex", None))
        self.radioButton_useMemoryLayer.setText(_translate("Form", "Memory Layer", None))
        self.radioButton_useActiveLayer.setText(_translate("Form", "Active Layer", None))
        self.label_5.setText(_translate("Form", "Coordinate System:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Drawing", None))
        self.groupBox1.setTitle(_translate("Form", "Drawing", None))
        self.arcNodesLabel.setToolTip(_translate("Form", "The more lines the smoother the arc will be", None))
        self.arcNodesLabel.setText(_translate("Form", "Arc lines", None))
        self.spin_arclines.setToolTip(_translate("Form", "The more lines the smoother the arc will be", None))
        self.checkBox_asSegments.setText(_translate("Form", "As Segments", None))
        self.checkBox_openForm.setText(_translate("Form", "Open attribute form", None))
        self.groupBox_3.setTitle(_translate("Form", "North type", None))
        self.radioButton_defaultNorth.setText(_translate("Form", "Default", None))
        self.radioButton_magNorth.setText(_translate("Form", "Magnetic", None))
        self.lineEdit_magNorth.setPlaceholderText(_translate("Form", "Magnetic offset", None))
        self.azimuth1_edit.setText(_translate("Form", "0", None))
        self.pickAngle1_button.setText(_translate("Form", "Pick Points", None))
        self.label_7.setText(_translate("Form", "Azimuth 2", None))
        self.azimuth2_edit.setText(_translate("Form", "0", None))
        self.pickAngle2_button.setText(_translate("Form", "Pick Points", None))
        self.label.setText(_translate("Form", "Azimuth Diff", None))
        self.copyDiff_button.setText(_translate("Form", "Use Value", None))
        self.label_8.setText(_translate("Form", "Azimuth 1", None))
        self.clearMarkers_button.setText(_translate("Form", "Clear angle markers", None))
        self.surveyGrpBox.setTitle(_translate("Form", "Survey type", None))
        self.radioButton_radialSurvey.setText(_translate("Form", "Polar / Radial", None))
        self.radioButton_boundarySurvey.setText(_translate("Form", "Boundary", None))
        self.groupBox_6.setTitle(_translate("Form", "Angle type", None))
        self.radioButton_azimuthAngle.setText(_translate("Form", "Azimuth", None))
        self.radioButton_bearingAngle.setText(_translate("Form", "Bearing", None))
        self.radioButton_polarCoordAngle.setText(_translate("Form", "Polar coordinates", None))
        self.groupBox_7.setTitle(_translate("Form", "Distance unit", None))
        self.radioButton_defaultUnits.setText(_translate("Form", "Default", None))
        self.radioButton_englishUnits.setText(_translate("Form", "Feet", None))
        self.groupBox_4.setTitle(_translate("Form", "Angle unit", None))
        self.radioButton_degreeUnit.setText(_translate("Form", "Degree", None))
        self.radioButton_gradianUnit.setText(_translate("Form", "Gradian", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Options", None))
        self.plainTextEdit_note.setPlainText(_translate("Form", "Angles may be entered as degrees clockwise from North (nnn.nn or nnd nn\' nn.n\") or as an offset bearing plus or minus 90 deg. from  North or South (N xxd xx\' xx\" E)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Help", None))

import resources_rc
