# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Sun Nov 08 11:43:25 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ui(object):
    def setupUi(self, ui):
        ui.setObjectName("ui")
        ui.resize(436, 489)
        self.label = QtGui.QLabel(ui)
        self.label.setGeometry(QtCore.QRect(10, 10, 56, 18))
        self.label.setObjectName("label")
        self.comboBox = QtGui.QComboBox(ui)
        self.comboBox.setGeometry(QtCore.QRect(90, 10, 341, 22))
        self.comboBox.setObjectName("comboBox")
        self.tableWidget = QtGui.QTableWidget(ui)
        self.tableWidget.setGeometry(QtCore.QRect(10, 320, 331, 131))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton_2 = QtGui.QPushButton(ui)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 320, 75, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(ui)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 460, 75, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(ui)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 390, 75, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(ui)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 420, 75, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(ui)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 460, 75, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox = QtGui.QGroupBox(ui)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 301, 111))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(70, 20, 113, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 50, 113, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 80, 113, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 21, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 60, 20, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 21, 18))
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtGui.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 20, 101, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtGui.QGroupBox(ui)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 101, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_7.setEnabled(True)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 30, 92, 24))
        self.radioButton_7.setCheckable(True)
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_8.setEnabled(True)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 10, 92, 24))
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.pushButton_7 = QtGui.QPushButton(ui)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 460, 75, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_4 = QtGui.QGroupBox(ui)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(120, 30, 171, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_11.setEnabled(True)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 30, 151, 24))
        self.radioButton_11.setCheckable(True)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_12.setEnabled(True)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 10, 151, 20))
        self.radioButton_12.setChecked(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_2 = QtGui.QGroupBox(ui)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 301, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 20, 113, 24))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 50, 113, 24))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 80, 113, 24))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 51, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 51, 18))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 41, 18))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(220, 80, 75, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 20, 101, 28))
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(ui)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL("clicked()"), self.tableWidget.clear)
        QtCore.QMetaObject.connectSlotsByName(ui)
        ui.setTabOrder(self.comboBox, self.lineEdit)
        ui.setTabOrder(self.lineEdit, self.lineEdit_2)
        ui.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        ui.setTabOrder(self.lineEdit_3, self.radioButton_8)
        ui.setTabOrder(self.radioButton_8, self.radioButton_7)
        ui.setTabOrder(self.radioButton_7, self.radioButton_12)
        ui.setTabOrder(self.radioButton_12, self.radioButton_11)
        ui.setTabOrder(self.radioButton_11, self.lineEdit_7)
        ui.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        ui.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        ui.setTabOrder(self.lineEdit_9, self.tableWidget)
        ui.setTabOrder(self.tableWidget, self.pushButton_2)
        ui.setTabOrder(self.pushButton_2, self.pushButton_4)
        ui.setTabOrder(self.pushButton_4, self.pushButton_5)
        ui.setTabOrder(self.pushButton_5, self.pushButton_6)
        ui.setTabOrder(self.pushButton_6, self.pushButton_3)
        ui.setTabOrder(self.pushButton_3, self.pushButton_7)

    def retranslateUi(self, ui):
        ui.setWindowTitle(QtGui.QApplication.translate("ui", "Geometry from Azimuth and Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ui", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ui", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ui", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ui", "Zenith", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("ui", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("ui", "Import List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("ui", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("ui", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("ui", "Clear List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ui", "Starting vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ui", "X0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ui", "Y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ui", "Z0:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("ui", "Capture from Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ui", "Survey type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("ui", "Irradiate", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("ui", "Polygonal", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("ui", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ui", "Input type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("ui", "Decimal Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("ui", "Degrees, Minutes, Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ui", "Next vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_7.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_9.setText(QtGui.QApplication.translate("ui", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ui", "Azimuth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ui", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ui", "Zenith:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ui", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("ui", "Capture from Map", None, QtGui.QApplication.UnicodeUTF8))

