# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Tue May 20 10:03:42 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ui(object):
    def setupUi(self, ui):
        ui.setObjectName(_fromUtf8("ui"))
        ui.resize(612, 685)
        self.verticalLayout_13 = QtGui.QVBoxLayout(ui)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.radioButton_useActiveLayer = QtGui.QRadioButton(ui)
        self.radioButton_useActiveLayer.setObjectName(_fromUtf8("radioButton_useActiveLayer"))
        self.verticalLayout_13.addWidget(self.radioButton_useActiveLayer)
        self.radioButton_useMemoryLayer = QtGui.QRadioButton(ui)
        self.radioButton_useMemoryLayer.setObjectName(_fromUtf8("radioButton_useMemoryLayer"))
        self.verticalLayout_13.addWidget(self.radioButton_useMemoryLayer)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_5 = QtGui.QLabel(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_14.addWidget(self.label_5)
        self.lineEdit_crs = QtGui.QLineEdit(ui)
        self.lineEdit_crs.setEnabled(False)
        self.lineEdit_crs.setObjectName(_fromUtf8("lineEdit_crs"))
        self.horizontalLayout_14.addWidget(self.lineEdit_crs)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.verticalLayout_13.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.plainTextEdit_note = QtGui.QPlainTextEdit(ui)
        self.plainTextEdit_note.setEnabled(True)
        self.plainTextEdit_note.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setReadOnly(True)
        self.plainTextEdit_note.setObjectName(_fromUtf8("plainTextEdit_note"))
        self.verticalLayout_6.addWidget(self.plainTextEdit_note)
        self.groupBox = QtGui.QGroupBox(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.lineEdit_vertexX0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexX0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexX0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexX0.setObjectName(_fromUtf8("lineEdit_vertexX0"))
        self.horizontalLayout_6.addWidget(self.lineEdit_vertexX0)
        self.pushButton_startCapture = QtGui.QPushButton(self.groupBox)
        self.pushButton_startCapture.setObjectName(_fromUtf8("pushButton_startCapture"))
        self.horizontalLayout_6.addWidget(self.pushButton_startCapture)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.lineEdit_vertexY0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexY0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexY0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexY0.setObjectName(_fromUtf8("lineEdit_vertexY0"))
        self.horizontalLayout_7.addWidget(self.lineEdit_vertexY0)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.lineEdit_vertexZ0 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_vertexZ0.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexZ0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexZ0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexZ0.setObjectName(_fromUtf8("lineEdit_vertexZ0"))
        self.horizontalLayout_8.addWidget(self.lineEdit_vertexZ0)
        spacerItem5 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.lineEdit_nextAzimuth = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextAzimuth.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextAzimuth.setSizePolicy(sizePolicy)
        self.lineEdit_nextAzimuth.setObjectName(_fromUtf8("lineEdit_nextAzimuth"))
        self.horizontalLayout_9.addWidget(self.lineEdit_nextAzimuth)
        self.pushButton_vertexAdd = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_vertexAdd.setObjectName(_fromUtf8("pushButton_vertexAdd"))
        self.horizontalLayout_9.addWidget(self.pushButton_vertexAdd)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_nextDistance = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextDistance.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextDistance.setSizePolicy(sizePolicy)
        self.lineEdit_nextDistance.setObjectName(_fromUtf8("lineEdit_nextDistance"))
        self.horizontalLayout_10.addWidget(self.lineEdit_nextDistance)
        spacerItem8 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem9 = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.lineEdit_nextVertical = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_nextVertical.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextVertical.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextVertical.setSizePolicy(sizePolicy)
        self.lineEdit_nextVertical.setObjectName(_fromUtf8("lineEdit_nextVertical"))
        self.horizontalLayout_11.addWidget(self.lineEdit_nextVertical)
        self.pushButton_vertexInsert = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_vertexInsert.setObjectName(_fromUtf8("pushButton_vertexInsert"))
        self.horizontalLayout_11.addWidget(self.pushButton_vertexInsert)
        spacerItem10 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.surveyGrpBox = QtGui.QGroupBox(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surveyGrpBox.sizePolicy().hasHeightForWidth())
        self.surveyGrpBox.setSizePolicy(sizePolicy)
        self.surveyGrpBox.setObjectName(_fromUtf8("surveyGrpBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.surveyGrpBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.radioButton_radialSurvey = QtGui.QRadioButton(self.surveyGrpBox)
        self.radioButton_radialSurvey.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_radialSurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_radialSurvey.setSizePolicy(sizePolicy)
        self.radioButton_radialSurvey.setCheckable(True)
        self.radioButton_radialSurvey.setChecked(False)
        self.radioButton_radialSurvey.setObjectName(_fromUtf8("radioButton_radialSurvey"))
        self.verticalLayout_10.addWidget(self.radioButton_radialSurvey)
        self.radioButton_boundarySurvey = QtGui.QRadioButton(self.surveyGrpBox)
        self.radioButton_boundarySurvey.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_boundarySurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_boundarySurvey.setSizePolicy(sizePolicy)
        self.radioButton_boundarySurvey.setChecked(True)
        self.radioButton_boundarySurvey.setObjectName(_fromUtf8("radioButton_boundarySurvey"))
        self.verticalLayout_10.addWidget(self.radioButton_boundarySurvey)
        self.verticalLayout_4.addWidget(self.surveyGrpBox)
        self.groupBox_3 = QtGui.QGroupBox(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.radioButton_defaultNorth = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_defaultNorth.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultNorth.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultNorth.setSizePolicy(sizePolicy)
        self.radioButton_defaultNorth.setCheckable(True)
        self.radioButton_defaultNorth.setChecked(True)
        self.radioButton_defaultNorth.setObjectName(_fromUtf8("radioButton_defaultNorth"))
        self.verticalLayout_12.addWidget(self.radioButton_defaultNorth)
        self.radioButton_magNorth = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_magNorth.setEnabled(True)
        self.radioButton_magNorth.setChecked(False)
        self.radioButton_magNorth.setObjectName(_fromUtf8("radioButton_magNorth"))
        self.verticalLayout_12.addWidget(self.radioButton_magNorth)
        self.lineEdit_magNorth = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_magNorth.sizePolicy().hasHeightForWidth())
        self.lineEdit_magNorth.setSizePolicy(sizePolicy)
        self.lineEdit_magNorth.setObjectName(_fromUtf8("lineEdit_magNorth"))
        self.verticalLayout_12.addWidget(self.lineEdit_magNorth)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_7 = QtGui.QGroupBox(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_defaultUnits = QtGui.QRadioButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultUnits.setSizePolicy(sizePolicy)
        self.radioButton_defaultUnits.setChecked(True)
        self.radioButton_defaultUnits.setObjectName(_fromUtf8("radioButton_defaultUnits"))
        self.horizontalLayout.addWidget(self.radioButton_defaultUnits)
        self.radioButton_englishUnits = QtGui.QRadioButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_englishUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_englishUnits.setSizePolicy(sizePolicy)
        self.radioButton_englishUnits.setObjectName(_fromUtf8("radioButton_englishUnits"))
        self.horizontalLayout.addWidget(self.radioButton_englishUnits)
        spacerItem11 = QtGui.QSpacerItem(0, 36, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(ui)
        self.groupBox_6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_azimuthAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_azimuthAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_azimuthAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_azimuthAngle.setSizePolicy(sizePolicy)
        self.radioButton_azimuthAngle.setCheckable(True)
        self.radioButton_azimuthAngle.setChecked(True)
        self.radioButton_azimuthAngle.setObjectName(_fromUtf8("radioButton_azimuthAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_azimuthAngle)
        self.radioButton_bearingAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_bearingAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_bearingAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_bearingAngle.setSizePolicy(sizePolicy)
        self.radioButton_bearingAngle.setChecked(False)
        self.radioButton_bearingAngle.setObjectName(_fromUtf8("radioButton_bearingAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_bearingAngle)
        self.radioButton_polarCoordAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_polarCoordAngle.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_polarCoordAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_polarCoordAngle.setSizePolicy(sizePolicy)
        self.radioButton_polarCoordAngle.setChecked(False)
        self.radioButton_polarCoordAngle.setObjectName(_fromUtf8("radioButton_polarCoordAngle"))
        self.verticalLayout_5.addWidget(self.radioButton_polarCoordAngle)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_8 = QtGui.QGroupBox(ui)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.table_segmentList = QtGui.QTableWidget(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_segmentList.sizePolicy().hasHeightForWidth())
        self.table_segmentList.setSizePolicy(sizePolicy)
        self.table_segmentList.setObjectName(_fromUtf8("table_segmentList"))
        self.table_segmentList.setColumnCount(3)
        self.table_segmentList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.table_segmentList)
        self.verticalLayout_11.addWidget(self.groupBox_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_segListLoad = QtGui.QPushButton(ui)
        self.pushButton_segListLoad.setEnabled(True)
        self.pushButton_segListLoad.setObjectName(_fromUtf8("pushButton_segListLoad"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListLoad)
        self.pushButton_segListSave = QtGui.QPushButton(ui)
        self.pushButton_segListSave.setEnabled(True)
        self.pushButton_segListSave.setObjectName(_fromUtf8("pushButton_segListSave"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListSave)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.pushButton_segListClear = QtGui.QPushButton(ui)
        self.pushButton_segListClear.setObjectName(_fromUtf8("pushButton_segListClear"))
        self.horizontalLayout_3.addWidget(self.pushButton_segListClear)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_segListRowUp = QtGui.QPushButton(ui)
        self.pushButton_segListRowUp.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowUp.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowUp.setSizePolicy(sizePolicy)
        self.pushButton_segListRowUp.setObjectName(_fromUtf8("pushButton_segListRowUp"))
        self.verticalLayout.addWidget(self.pushButton_segListRowUp)
        self.pushButton_segListRowDn = QtGui.QPushButton(ui)
        self.pushButton_segListRowDn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDn.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDn.setSizePolicy(sizePolicy)
        self.pushButton_segListRowDn.setObjectName(_fromUtf8("pushButton_segListRowDn"))
        self.verticalLayout.addWidget(self.pushButton_segListRowDn)
        spacerItem13 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.pushButton_segListRowDel = QtGui.QPushButton(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segListRowDel.sizePolicy().hasHeightForWidth())
        self.pushButton_segListRowDel.setSizePolicy(sizePolicy)
        self.pushButton_segListRowDel.setObjectName(_fromUtf8("pushButton_segListRowDel"))
        self.verticalLayout.addWidget(self.pushButton_segListRowDel)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_objectDraw = QtGui.QPushButton(ui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_objectDraw.sizePolicy().hasHeightForWidth())
        self.pushButton_objectDraw.setSizePolicy(sizePolicy)
        self.pushButton_objectDraw.setObjectName(_fromUtf8("pushButton_objectDraw"))
        self.verticalLayout_2.addWidget(self.pushButton_objectDraw)
        spacerItem14 = QtGui.QSpacerItem(28, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.pushButton_dlgClose = QtGui.QPushButton(ui)
        self.pushButton_dlgClose.setObjectName(_fromUtf8("pushButton_dlgClose"))
        self.verticalLayout_2.addWidget(self.pushButton_dlgClose)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.label_5.setBuddy(self.lineEdit_crs)
        self.label_2.setBuddy(self.lineEdit_vertexX0)
        self.label_3.setBuddy(self.lineEdit_vertexY0)
        self.label_4.setBuddy(self.lineEdit_vertexZ0)
        self.label_8.setBuddy(self.lineEdit_nextAzimuth)
        self.label_9.setBuddy(self.lineEdit_nextDistance)
        self.label_10.setBuddy(self.lineEdit_nextVertical)

        self.retranslateUi(ui)
        QtCore.QObject.connect(self.pushButton_dlgClose, QtCore.SIGNAL(_fromUtf8("clicked()")), ui.reject)
        QtCore.QMetaObject.connectSlotsByName(ui)
        ui.setTabOrder(self.lineEdit_vertexX0, self.lineEdit_vertexY0)
        ui.setTabOrder(self.lineEdit_vertexY0, self.pushButton_startCapture)
        ui.setTabOrder(self.pushButton_startCapture, self.lineEdit_nextAzimuth)
        ui.setTabOrder(self.lineEdit_nextAzimuth, self.lineEdit_nextDistance)
        ui.setTabOrder(self.lineEdit_nextDistance, self.pushButton_vertexAdd)
        ui.setTabOrder(self.pushButton_vertexAdd, self.radioButton_radialSurvey)
        ui.setTabOrder(self.radioButton_radialSurvey, self.radioButton_boundarySurvey)
        ui.setTabOrder(self.radioButton_boundarySurvey, self.radioButton_defaultNorth)
        ui.setTabOrder(self.radioButton_defaultNorth, self.radioButton_magNorth)
        ui.setTabOrder(self.radioButton_magNorth, self.lineEdit_magNorth)
        ui.setTabOrder(self.lineEdit_magNorth, self.radioButton_defaultUnits)
        ui.setTabOrder(self.radioButton_defaultUnits, self.radioButton_englishUnits)
        ui.setTabOrder(self.radioButton_englishUnits, self.radioButton_azimuthAngle)
        ui.setTabOrder(self.radioButton_azimuthAngle, self.radioButton_bearingAngle)
        ui.setTabOrder(self.radioButton_bearingAngle, self.radioButton_polarCoordAngle)
        ui.setTabOrder(self.radioButton_polarCoordAngle, self.pushButton_objectDraw)
        ui.setTabOrder(self.pushButton_objectDraw, self.pushButton_segListSave)
        ui.setTabOrder(self.pushButton_segListSave, self.pushButton_dlgClose)
        ui.setTabOrder(self.pushButton_dlgClose, self.lineEdit_crs)
        ui.setTabOrder(self.lineEdit_crs, self.pushButton_vertexInsert)
        ui.setTabOrder(self.pushButton_vertexInsert, self.table_segmentList)
        ui.setTabOrder(self.table_segmentList, self.pushButton_segListLoad)
        ui.setTabOrder(self.pushButton_segListLoad, self.pushButton_segListClear)
        ui.setTabOrder(self.pushButton_segListClear, self.pushButton_segListRowUp)
        ui.setTabOrder(self.pushButton_segListRowUp, self.pushButton_segListRowDn)
        ui.setTabOrder(self.pushButton_segListRowDn, self.pushButton_segListRowDel)
        ui.setTabOrder(self.pushButton_segListRowDel, self.plainTextEdit_note)
        ui.setTabOrder(self.plainTextEdit_note, self.lineEdit_nextVertical)
        ui.setTabOrder(self.lineEdit_nextVertical, self.lineEdit_vertexZ0)

    def retranslateUi(self, ui):
        ui.setWindowTitle(QtGui.QApplication.translate("ui", "Geometry from Azimuth and Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_useActiveLayer.setText(QtGui.QApplication.translate("ui", "Active Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_useMemoryLayer.setText(QtGui.QApplication.translate("ui", "Memory Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ui", "Coordinate System:", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_note.setPlainText(QtGui.QApplication.translate("ui", "Angles may be entered as degrees clockwise from North (nnn.nn or nnd nn\' nn.n\") or as an offset bearing plus or minus 90 deg. from  North or South (N xxd xx\' xx\" E)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ui", "Starting vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ui", "X0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexX0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_startCapture.setText(QtGui.QApplication.translate("ui", "Capture from Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ui", "Y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexY0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ui", "Z0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexZ0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ui", "Next vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ui", "Azimuth:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextAzimuth.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_vertexAdd.setText(QtGui.QApplication.translate("ui", "Add to Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ui", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextDistance.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ui", "Vertical:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextVertical.setText(QtGui.QApplication.translate("ui", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_vertexInsert.setText(QtGui.QApplication.translate("ui", "Insert above", None, QtGui.QApplication.UnicodeUTF8))
        self.surveyGrpBox.setTitle(QtGui.QApplication.translate("ui", "Survey type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_radialSurvey.setText(QtGui.QApplication.translate("ui", "Polar / Radial", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_boundarySurvey.setText(QtGui.QApplication.translate("ui", "Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ui", "North type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_defaultNorth.setText(QtGui.QApplication.translate("ui", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_magNorth.setText(QtGui.QApplication.translate("ui", "Magnetic", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_magNorth.setText(QtGui.QApplication.translate("ui", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("ui", "Distance units", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_defaultUnits.setText(QtGui.QApplication.translate("ui", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_englishUnits.setText(QtGui.QApplication.translate("ui", "Feet", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("ui", "Angle type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_azimuthAngle.setText(QtGui.QApplication.translate("ui", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bearingAngle.setText(QtGui.QApplication.translate("ui", "Bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_polarCoordAngle.setText(QtGui.QApplication.translate("ui", "Polar coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("ui", "Segment List", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ui", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ui", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ui", "Vertical Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListLoad.setText(QtGui.QApplication.translate("ui", "Import List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListSave.setText(QtGui.QApplication.translate("ui", "Export List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListClear.setText(QtGui.QApplication.translate("ui", "Clear List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowUp.setText(QtGui.QApplication.translate("ui", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowDn.setText(QtGui.QApplication.translate("ui", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowDel.setText(QtGui.QApplication.translate("ui", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_objectDraw.setText(QtGui.QApplication.translate("ui", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dlgClose.setText(QtGui.QApplication.translate("ui", "Close", None, QtGui.QApplication.UnicodeUTF8))

