# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\flaplante.FLOS-INC\.qgis\python\plugins\qgsazimuth\ui.ui'
#
# Created: Mon Nov 30 23:12:34 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ui(object):
    def setupUi(self, ui):
        ui.setObjectName("ui")
        ui.resize(563, 674)
        self.plainTextEdit_note = QtGui.QPlainTextEdit(ui)
        self.plainTextEdit_note.setEnabled(True)
        self.plainTextEdit_note.setGeometry(QtCore.QRect(10, 90, 301, 61))
        self.plainTextEdit_note.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_note.setReadOnly(True)
        self.plainTextEdit_note.setObjectName("plainTextEdit_note")
        self.widget = QtGui.QWidget(ui)
        self.widget.setGeometry(QtCore.QRect(9, 9, 541, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.comboBox_layers = QtGui.QComboBox(self.widget)
        self.comboBox_layers.setObjectName("comboBox_layers")
        self.horizontalLayout_13.addWidget(self.comboBox_layers)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.lineEdit_crs = QtGui.QLineEdit(self.widget)
        self.lineEdit_crs.setEnabled(False)
        self.lineEdit_crs.setObjectName("lineEdit_crs")
        self.horizontalLayout_14.addWidget(self.lineEdit_crs)
        self.pushButton_crsChg = QtGui.QPushButton(self.widget)
        self.pushButton_crsChg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_crsChg.sizePolicy().hasHeightForWidth())
        self.pushButton_crsChg.setSizePolicy(sizePolicy)
        self.pushButton_crsChg.setObjectName("pushButton_crsChg")
        self.horizontalLayout_14.addWidget(self.pushButton_crsChg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.groupBox_6 = QtGui.QGroupBox(ui)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setGeometry(QtCore.QRect(330, 314, 221, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_azimuthAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_azimuthAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_azimuthAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_azimuthAngle.setSizePolicy(sizePolicy)
        self.radioButton_azimuthAngle.setCheckable(True)
        self.radioButton_azimuthAngle.setChecked(True)
        self.radioButton_azimuthAngle.setObjectName("radioButton_azimuthAngle")
        self.verticalLayout_5.addWidget(self.radioButton_azimuthAngle)
        self.radioButton_bearingAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_bearingAngle.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_bearingAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_bearingAngle.setSizePolicy(sizePolicy)
        self.radioButton_bearingAngle.setChecked(False)
        self.radioButton_bearingAngle.setObjectName("radioButton_bearingAngle")
        self.verticalLayout_5.addWidget(self.radioButton_bearingAngle)
        self.radioButton_polarCoordAngle = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_polarCoordAngle.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_polarCoordAngle.sizePolicy().hasHeightForWidth())
        self.radioButton_polarCoordAngle.setSizePolicy(sizePolicy)
        self.radioButton_polarCoordAngle.setChecked(False)
        self.radioButton_polarCoordAngle.setObjectName("radioButton_polarCoordAngle")
        self.verticalLayout_5.addWidget(self.radioButton_polarCoordAngle)
        self.groupBox = QtGui.QGroupBox(ui)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 301, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.lineEdit_vertexX0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexX0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexX0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexX0.setObjectName("lineEdit_vertexX0")
        self.horizontalLayout_6.addWidget(self.lineEdit_vertexX0)
        self.pushButton_startCapture = QtGui.QPushButton(self.groupBox)
        self.pushButton_startCapture.setObjectName("pushButton_startCapture")
        self.horizontalLayout_6.addWidget(self.pushButton_startCapture)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.lineEdit_vertexY0 = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexY0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexY0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexY0.setObjectName("lineEdit_vertexY0")
        self.horizontalLayout_7.addWidget(self.lineEdit_vertexY0)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.lineEdit_vertexZ0 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_vertexZ0.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vertexZ0.sizePolicy().hasHeightForWidth())
        self.lineEdit_vertexZ0.setSizePolicy(sizePolicy)
        self.lineEdit_vertexZ0.setObjectName("lineEdit_vertexZ0")
        self.horizontalLayout_8.addWidget(self.lineEdit_vertexZ0)
        spacerItem5 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.groupBox_2 = QtGui.QGroupBox(ui)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 301, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.lineEdit_nextAzimuth = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextAzimuth.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextAzimuth.setSizePolicy(sizePolicy)
        self.lineEdit_nextAzimuth.setObjectName("lineEdit_nextAzimuth")
        self.horizontalLayout_9.addWidget(self.lineEdit_nextAzimuth)
        spacerItem7 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_nextDistance = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextDistance.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextDistance.setSizePolicy(sizePolicy)
        self.lineEdit_nextDistance.setObjectName("lineEdit_nextDistance")
        self.horizontalLayout_10.addWidget(self.lineEdit_nextDistance)
        spacerItem8 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem9 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.lineEdit_nextVertical = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_nextVertical.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nextVertical.sizePolicy().hasHeightForWidth())
        self.lineEdit_nextVertical.setSizePolicy(sizePolicy)
        self.lineEdit_nextVertical.setObjectName("lineEdit_nextVertical")
        self.horizontalLayout_11.addWidget(self.lineEdit_nextVertical)
        spacerItem10 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.pushButton_vertexInsert = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_vertexInsert.setObjectName("pushButton_vertexInsert")
        self.horizontalLayout_11.addWidget(self.pushButton_vertexInsert)
        spacerItem11 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.surveyGrpBox = QtGui.QGroupBox(ui)
        self.surveyGrpBox.setGeometry(QtCore.QRect(330, 80, 221, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surveyGrpBox.sizePolicy().hasHeightForWidth())
        self.surveyGrpBox.setSizePolicy(sizePolicy)
        self.surveyGrpBox.setObjectName("surveyGrpBox")
        self.layoutWidget = QtGui.QWidget(self.surveyGrpBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 241, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_polySurvey = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_polySurvey.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_polySurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_polySurvey.setSizePolicy(sizePolicy)
        self.radioButton_polySurvey.setChecked(True)
        self.radioButton_polySurvey.setObjectName("radioButton_polySurvey")
        self.horizontalLayout.addWidget(self.radioButton_polySurvey)
        self.radioButton_irrSurvey = QtGui.QRadioButton(self.layoutWidget)
        self.radioButton_irrSurvey.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_irrSurvey.sizePolicy().hasHeightForWidth())
        self.radioButton_irrSurvey.setSizePolicy(sizePolicy)
        self.radioButton_irrSurvey.setCheckable(True)
        self.radioButton_irrSurvey.setChecked(False)
        self.radioButton_irrSurvey.setObjectName("radioButton_irrSurvey")
        self.horizontalLayout.addWidget(self.radioButton_irrSurvey)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.groupBox_3 = QtGui.QGroupBox(ui)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 150, 221, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 17, 191, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_defaultNorth = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_defaultNorth.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultNorth.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultNorth.setSizePolicy(sizePolicy)
        self.radioButton_defaultNorth.setCheckable(True)
        self.radioButton_defaultNorth.setChecked(True)
        self.radioButton_defaultNorth.setObjectName("radioButton_defaultNorth")
        self.gridLayout.addWidget(self.radioButton_defaultNorth, 0, 0, 1, 1)
        self.radioButton_magNorth = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_magNorth.setEnabled(True)
        self.radioButton_magNorth.setChecked(False)
        self.radioButton_magNorth.setObjectName("radioButton_magNorth")
        self.gridLayout.addWidget(self.radioButton_magNorth, 1, 0, 1, 1)
        self.lineEdit_magNorth = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_magNorth.sizePolicy().hasHeightForWidth())
        self.lineEdit_magNorth.setSizePolicy(sizePolicy)
        self.lineEdit_magNorth.setObjectName("lineEdit_magNorth")
        self.gridLayout.addWidget(self.lineEdit_magNorth, 1, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(ui)
        self.groupBox_7.setGeometry(QtCore.QRect(330, 240, 221, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_defaultUnits = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_defaultUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_defaultUnits.setSizePolicy(sizePolicy)
        self.radioButton_defaultUnits.setObjectName("radioButton_defaultUnits")
        self.horizontalLayout_2.addWidget(self.radioButton_defaultUnits)
        self.radioButton_englishUnits = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_englishUnits.sizePolicy().hasHeightForWidth())
        self.radioButton_englishUnits.setSizePolicy(sizePolicy)
        self.radioButton_englishUnits.setObjectName("radioButton_englishUnits")
        self.horizontalLayout_2.addWidget(self.radioButton_englishUnits)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.widget1 = QtGui.QWidget(ui)
        self.widget1.setGeometry(QtCore.QRect(470, 430, 79, 231))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_objectDraw = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_objectDraw.sizePolicy().hasHeightForWidth())
        self.pushButton_objectDraw.setSizePolicy(sizePolicy)
        self.pushButton_objectDraw.setObjectName("pushButton_objectDraw")
        self.verticalLayout_2.addWidget(self.pushButton_objectDraw)
        spacerItem14 = QtGui.QSpacerItem(28, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.pushButton_dlgClose = QtGui.QPushButton(self.widget1)
        self.pushButton_dlgClose.setObjectName("pushButton_dlgClose")
        self.verticalLayout_2.addWidget(self.pushButton_dlgClose)
        self.groupBox_8 = QtGui.QGroupBox(ui)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 420, 441, 181))
        self.groupBox_8.setObjectName("groupBox_8")
        self.table_segmentList = QtGui.QTableWidget(self.groupBox_8)
        self.table_segmentList.setGeometry(QtCore.QRect(10, 20, 331, 151))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_segmentList.sizePolicy().hasHeightForWidth())
        self.table_segmentList.setSizePolicy(sizePolicy)
        self.table_segmentList.setObjectName("table_segmentList")
        self.table_segmentList.setColumnCount(3)
        self.table_segmentList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_segmentList.setHorizontalHeaderItem(2, item)
        self.widget2 = QtGui.QWidget(self.groupBox_8)
        self.widget2.setGeometry(QtCore.QRect(350, 20, 79, 151))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_segListRowUp = QtGui.QPushButton(self.widget2)
        self.pushButton_segListRowUp.setEnabled(False)
        self.pushButton_segListRowUp.setObjectName("pushButton_segListRowUp")
        self.verticalLayout.addWidget(self.pushButton_segListRowUp)
        self.pushButton_segListRowDn = QtGui.QPushButton(self.widget2)
        self.pushButton_segListRowDn.setEnabled(False)
        self.pushButton_segListRowDn.setObjectName("pushButton_segListRowDn")
        self.verticalLayout.addWidget(self.pushButton_segListRowDn)
        spacerItem15 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.pushButton_segListRowDel = QtGui.QPushButton(self.widget2)
        self.pushButton_segListRowDel.setObjectName("pushButton_segListRowDel")
        self.verticalLayout.addWidget(self.pushButton_segListRowDel)
        self.groupBox_4 = QtGui.QGroupBox(ui)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 610, 441, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget3 = QtGui.QWidget(self.groupBox_4)
        self.widget3.setGeometry(QtCore.QRect(10, 7, 421, 41))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_segListLoad = QtGui.QPushButton(self.widget3)
        self.pushButton_segListLoad.setEnabled(True)
        self.pushButton_segListLoad.setObjectName("pushButton_segListLoad")
        self.horizontalLayout_3.addWidget(self.pushButton_segListLoad)
        self.pushButton_segListSave = QtGui.QPushButton(self.widget3)
        self.pushButton_segListSave.setEnabled(True)
        self.pushButton_segListSave.setObjectName("pushButton_segListSave")
        self.horizontalLayout_3.addWidget(self.pushButton_segListSave)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.pushButton_segListClear = QtGui.QPushButton(self.widget3)
        self.pushButton_segListClear.setObjectName("pushButton_segListClear")
        self.horizontalLayout_3.addWidget(self.pushButton_segListClear)
        self.label_2.setBuddy(self.lineEdit_vertexX0)
        self.label_3.setBuddy(self.lineEdit_vertexY0)
        self.label_4.setBuddy(self.lineEdit_vertexZ0)
        self.label_8.setBuddy(self.lineEdit_nextAzimuth)
        self.label_9.setBuddy(self.lineEdit_nextDistance)
        self.label_10.setBuddy(self.lineEdit_nextVertical)

        self.retranslateUi(ui)
        QtCore.QObject.connect(self.pushButton_dlgClose, QtCore.SIGNAL("clicked()"), ui.reject)
        QtCore.QMetaObject.connectSlotsByName(ui)
        ui.setTabOrder(self.comboBox_layers, self.lineEdit_vertexX0)
        ui.setTabOrder(self.lineEdit_vertexX0, self.lineEdit_vertexY0)
        ui.setTabOrder(self.lineEdit_vertexY0, self.lineEdit_vertexZ0)
        ui.setTabOrder(self.lineEdit_vertexZ0, self.lineEdit_nextAzimuth)
        ui.setTabOrder(self.lineEdit_nextAzimuth, self.lineEdit_nextDistance)
        ui.setTabOrder(self.lineEdit_nextDistance, self.lineEdit_nextVertical)

    def retranslateUi(self, ui):
        ui.setWindowTitle(QtGui.QApplication.translate("ui", "Geometry from Azimuth and Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_note.setPlainText(QtGui.QApplication.translate("ui", "Angles may be entered as degrees clockwise from North (nnn.nn or nnd nn\' nn.n\") or as an offset bearing plus or minus 90 deg. from  North or South (N xxd xx\' xx\" E)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ui", "Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ui", "Coordinate System:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crsChg.setText(QtGui.QApplication.translate("ui", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("ui", "Angle type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_azimuthAngle.setText(QtGui.QApplication.translate("ui", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bearingAngle.setText(QtGui.QApplication.translate("ui", "Bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_polarCoordAngle.setText(QtGui.QApplication.translate("ui", "Polar coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ui", "Starting vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ui", "X0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexX0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_startCapture.setText(QtGui.QApplication.translate("ui", "Capture from Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ui", "Y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexY0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ui", "Z0:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vertexZ0.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ui", "Next vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ui", "Azimuth:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextAzimuth.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ui", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextDistance.setText(QtGui.QApplication.translate("ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ui", "Vertical:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nextVertical.setText(QtGui.QApplication.translate("ui", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_vertexInsert.setText(QtGui.QApplication.translate("ui", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.surveyGrpBox.setTitle(QtGui.QApplication.translate("ui", "Survey type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_polySurvey.setText(QtGui.QApplication.translate("ui", "Polygonal", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_irrSurvey.setText(QtGui.QApplication.translate("ui", "Irradiate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ui", "North type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_defaultNorth.setText(QtGui.QApplication.translate("ui", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_magNorth.setText(QtGui.QApplication.translate("ui", "Magnetic", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_magNorth.setText(QtGui.QApplication.translate("ui", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("ui", "Distance units", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_defaultUnits.setText(QtGui.QApplication.translate("ui", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_englishUnits.setText(QtGui.QApplication.translate("ui", "Feet", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_objectDraw.setText(QtGui.QApplication.translate("ui", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dlgClose.setText(QtGui.QApplication.translate("ui", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("ui", "Segment List", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ui", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ui", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.table_segmentList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ui", "Vertical Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowUp.setText(QtGui.QApplication.translate("ui", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowDn.setText(QtGui.QApplication.translate("ui", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListRowDel.setText(QtGui.QApplication.translate("ui", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListLoad.setText(QtGui.QApplication.translate("ui", "Import List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListSave.setText(QtGui.QApplication.translate("ui", "Export List", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segListClear.setText(QtGui.QApplication.translate("ui", "Clear List", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ui = QtGui.QDialog()
    ui = Ui_ui()
    ui.setupUi(ui)
    ui.show()
    sys.exit(app.exec_())

